channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - dash=2.14.2
  - flask=3.0.3
  - flask-compress=1.13
  - ipython=8.12.2
  - imageio=2.36.0
  - imagecodecs=2023.1.23
  - opencv=4.7.0
  - einops=0.8.0
  - matplotlib
  - numpy
  - pandas
  - scipy
  - pip:
      - filterpy
      - filterpy==1.4.5
